### ISSUE TITLE
Is this possible to compile on other promenient Linux distributions?

### ISSUE THREAD

**Issue by Impeta** [HaikuArchives/ffmpegGUI#115]
Sorry for any of the following obvious ill-literacy on UNIX generally, but I was hoping to compile it in my EndeavourOS (Arch-based) system, though I get the following error:
```
/bin/sh: line 1: findpaths: command not found
Makefile:140: /etc/makefile-engine: No such file or directory
make: *** No rule to make target '/etc/makefile-engine'.  Stop.
```
Is it possible to use on other distros beyond Haiku?

**Comment by humdingerb** [comment]
ffmpegGUI only runs on Haiku. Haiku is not a Linux distro, see https://www.haiku-os.org/ for more info.
