### ISSUE TITLE
Label for Reset-Button (in cropping tab) not translated into German

### ISSUE THREAD

**Issue by andimachovec** [HaikuArchives/ffmpegGUI#120]
It still says "Reset". Should be something like "Zurücksetzen". 
I don't have the permissions on Polyglot to change it, otherwise I would have done it myself

@humdinger: Could you change that please

**Comment by humdingerb** [comment]
I thought "Reset" was generally accepted in German computer lingo, and is nice and short, so I left it as is.
But upon further reflection and consulting the translations of other "resets" in Haiku, I now concur. Changed it to "Zurücksetzen" at Polyglot, so it'll get applied with the next catkeys update. Save to mark this ticket as fixed, I suppose.

I granted you German permissions at Polyglot for any future fixes.

**Comment by andimachovec** [comment]
In this case I think it's better to translate it. But carefully thinking about whether to translate is a good thing, to avoid "over-translating" (like in Debian where I nearly had to switch back to English to understand some error messages)
Thanks for granting me the permissions.
