### ISSUE TITLE
Update crop option to show frame view and crop region

### ISSUE THREAD

**Issue by scottmc** [HaikuArchives/ffmpegGUI#28]
Update the crop feature to show a current frame view and a border around the currently selected crop region.

**Comment by andimachovec** [comment]
@humdinger: What do you think of this one? Would probably be handy to see where the cropping will occur beforehand. I've already implemented a basic view class to do this but I have no real good idea where to put it in our interface. Maybe a separate "Cropping" tab?

**Comment by humdingerb** [comment]
I don't think it'll fit as tab in the main window. I'd propose a separate window opened with a "Preview" button below the crop coordinates.
Do you plan so set the crop parameters within that preview window? That would nicer than a passive preview. :)
In any case, such a preview would benefit greatly, having a slider to scrub through the video. The user may want to make sure the cropping doesn't cut too much of some frame of the video.
We're getting dangerously close to video editing territory, though. :)

**Comment by andimachovec** [comment]
> Do you plan so set the crop parameters within that preview window? That would nicer than a passive preview. :)

Not initially, but I've thought about it. Would sure be nice and more importantly (for me) an interesting challenge to implement ;-)


> In any case, such a preview would benefit greatly, having a slider to scrub through the video. The user may want to make sure the cropping doesn't cut too much of some frame of the video.
> We're getting dangerously close to video editing territory, though. :)

Yep, that's exactly why I wanted to start this discussion here. ffmpegGUI in my view is a simple frontend for people that are uncomfortable with the commandline and/or overwhelmed by the options of ffmpeg. Since we already have a native video editor with Medo, we should stay clear of making one out of ffmpegGUI. Long story short, I don't think we should add frame by frame scrolling, which is by the way also proposed in one of the other enhancement issues.

**Comment by humdingerb** [comment]
We're on the page then. What's your plan WRT cropping preview then?
* Extract a frame of the video with ffmpeg and show it in a window (after clicking a "Preview" button) with the crop parameters as overlayed lines.
* Second goal: let the user grab those lines and move them around, updating the crop parameters.

Every click on "Preview" could extract a random frame near the middle of the video. That way, in case you accidentally grab a frame that's unsuited (very dark, or the same colour as the crop-lines, etc...), you just click "Preview" again for a hopefully better one.

**Comment by andimachovec** [comment]
> We're on the same page then. What's your plan WRT cropping preview then?
> 
>     * Extract a frame of the video with ffmpeg and show it in a window (after clicking a "Preview" button) with the crop parameters as overlayed lines.
> 
>     * Second goal: let the user grab those lines and move them around, updating the crop parameters.

Yep, that's the plan basically. Here's how it looks in my little test app:
![cropping](https://user-images.githubusercontent.com/26166277/222006626-e8bc9bde-9f8d-4613-9dbb-a532f91e55dd.png)

The image is scaled to the view size preserving aspect ratio, the position and size of the cropping frame takes the scaling factor into account. 

I'm still not completely convinced ffmpegGUI really needs this feature though. :-)

**Comment by humdingerb** [comment]
> I'm still not completely convinced ffmpegGUI really needs this feature though. :-)

Up to you, of course. But at this stage, the whole crop settings are a bit impractical. You have to set the cropping values blindly or with try and error. Or you have to play your clip in MediaPlayer, pause, take a screenshot, open ArtPaint, do the cropping there, calculate the crop parameters and enter them in fmpegGUI...

Maybe the whole cropping business is better left to Medo...

**Comment by andimachovec** [comment]
This can be closed
