### ISSUE TITLE
Encoding fails when source or output file names contain spaces

### ISSUE THREAD

**Issue by andimachovec** [HaikuArchives/ffmpegGUI#29]
The file names have to be quoted in the ffmpeg commandline which is not the case at the moment

**Comment by scottmc** [comment]
Also need to test for invalid characters in the filenames and perhaps substitute in "_" or some other char.  For example "/" might end up spitting the file and putting the result into a newly create subdirectory.  See https://github.com/HaikuArchives/Hare/issues/49 for a similar issue we ran into on Hare.

**Comment by andimachovec** [comment]
Not sure about replacing the slash character. As of now we have full pathnames in the input and output file name fields, so it's inevitable that they contain slashes.

**Comment by scottmc** [comment]
> Not sure about replacing the slash character. As of now we have full pathnames in the input and output file name fields, so it's inevitable that they contain slashes.

Good point.  The slashes in the case of Hare were getting pulled in from the Song names, some of which have slashes in them.  That shouldn't be the case here.
