### ISSUE TITLE
Using the increase and decrease buttons is buggy

### ISSUE THREAD

**Issue by redsPL** [HaikuArchives/ffmpegGUI#3]
![](http://f.sakamoto.pl/9fd6b030-5522-434f-8254-aac23da5181cfile_56.jpg)

Those inputs start out as blank, and after clicking the up or the down arrow, they don't seem to do anything (they stay clear OR clear the input if there was anything in them). The only indicator that they work is ffmpeg's parameters in the Encode textbox, as they change with every press.

Also, when inputting a number by hand, it doesn't get accepted until you press enter.

**Comment by diversys** [comment]
Selecting such inputs and moving cursor to the right reveals values. Could also be a problem in Haiku.

**Comment by redsPL** [comment]
It appears that the box input box is somehow too large and the text aligning itself to the center (try dragging the input box with a mouse to the left or to the right). It's either a Haiku bug, or it might be just a problem with this GUI.

**Comment by redsPL** [comment]
![](http://f.sakamoto.pl/8b00e2f8-aec3-439b-98d2-1067c2cc6775file_59.jpg)
I've done some investigating, and it seems that the issue is a problem in PulkoMandy's liblayout. Originally, these two had labels `X Resolution` and `Y Resolution` respectively, because `Width` and `Height` are shorter, the issue doesn't persist. The mitigation would be probably to add some sort of spacers preventing the UI from overflowing, but I don't think that it's the most important thing in the world.

If there isn't an issue on PulkoMandy's repo, I'll be sending one shortly. If you have no objections, I'd be willing to close this issue.
