### ISSUE TITLE
Make a release and add future milestones

### ISSUE THREAD

**Issue by scottmc** [HaikuArchives/ffmpegGUI#31]
Once this app reaches a point where it is useful and doesn't have any nasty crashes we should do a release.  We should also review the open issues and create milestones for future releases.

**Comment by andimachovec** [comment]
Before we can make the first release somebody has to look at the ffmpeg options and check if they are working or not. (and why). For example using mkv as output file format doesn't work on my system. I don't really have that much knowledge about ffmpeg, maybe someone else can do that ;-)

**Comment by scottmc** [comment]
@vidrep @owenca @humdingerb @deepango @diversys @janus2 maybe you can take a look at ffmpegGUI as it is now and check it over for us?  It would help to have a few extra eyes on it prior to it's release.

**Comment by humdingerb** [comment]
I created PR #41 with some minor adjustments of the GUI. If merged I can add it to Polyglot for translation, even if the first release might not include those yet, if you want to release soon.
I'm not much of an ffmpeg user or video in general, but I'll have a look if it all seems to work.

**Comment by andimachovec** [comment]
I think we are slowly getting there ;-) I´d like to finish the code cleanup (almost done) and the code style cleanup before 1.1 so we can continue with the code base in good condition. And the cropping issues reported in #46 need to be addressed before a release. 
@humdingerb or @scottmc : Could you attach the 1.1 milestone to the issues #46 , #51 #52 and #53 please?

**Comment by humdingerb** [comment]
@andimachovec , what's your take on putting out a release soon?
I think we got much done now, and the app is quite nice and useful already. I'd say we do some codec testing, remove what doesn't work and give translations at Polyglot a week or so.

**Comment by andimachovec** [comment]
Completely agree, I think we're definitely ready for a release (once at least most of the translations have been updated). 
Quite some progress that we made with this little app in the last months.

**Comment by andimachovec** [comment]
@humdingerb : before I forget it. Please add yourself to the authors list in the about dialog, you've put a lot of work into this app.

**Comment by humdingerb** [comment]
Thanks. Will do. :)

**Comment by humdingerb** [comment]
I'll creating release v1.1 soon. If something needs to make it in urgently or should prevent the release, do speak up now. :)

**Comment by andimachovec** [comment]
We should add HandMaus to the credits in the about dialog for designing the icon. 
That´s about it from me. Looking forward to the release!

**Comment by humdingerb** [comment]
All done. Onwards to v1.2... :)
