### ISSUE TITLE
"Delete source when finished" checkbox has no effect

### ISSUE THREAD

**Issue by andimachovec** [HaikuArchives/ffmpegGUI#32]
This checkbox currently has no effect. The implementation should check the success status of the encoding and only delete the source file if the operation was successful.
Or we could remove the checkbox entirely and let the user delete the files manually.

**Comment by scottmc** [comment]
I vote for the latter.  I see no need for this, as you said if the user no longer wants the originals they can delete them manually.  I usually keep mine until I check the output.

**Comment by scottmc** [comment]
@andimachovec  I've added milestones 1.1 and 1.2, feel free to rename them and/or reassign open issues as you see fit.  I picked 1.1 as I think the current about calls the current version 1.0?

**Comment by andimachovec** [comment]
> I vote for the latter

Yeah, me too. Deleting files is outside the scope of this app. Can be done in Tracker :-)
I´ll remove the checkbox.
