### ISSUE TITLE
ffmpegGUI could use an HVIF icon

### ISSUE THREAD

**Issue by scottmc** [HaikuArchives/ffmpegGUI#39]

**Comment by scottmc** [comment]
Some discussion on Haiku Forums
https://discuss.haiku-os.org/t/just-some-icons/12721/30
Anyone have ffmpegGUI icon ideas?

**Comment by humdingerb** [comment]
[Handmaus' icon](https://discuss.haiku-os.org/t/just-some-icons/12721/33) doesn't look too bad. Maybe without the mouse for lower resolutions or at all.

**Comment by andimachovec** [comment]
Done and can be closed
