### ISSUE TITLE
Cropping issues

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ffmpegGUI#46]
Did some crop testing with a file Test.mp4, resolution 608 x 1080, always cropping 200 pixels.

* Cropping 200 pixels from the **top** doesn't actually crop at all
   > ffmpeg -i "/boot/home/Desktop/Test.mp4" -f avi -vcodec mpeg4 -b:v 1000 -r 30 -vf crop=w=in_w:h=in_h:x=0:y=200 -acodec ac3 -b:a 128 -ar 44100 -ac 2 "/boot/home/Desktop/Test.avi"

* Cropping 200 pixels from the **bottom** works
   > ffmpeg -i "/boot/home/Desktop/Test.mp4" -f avi -vcodec mpeg4 -b:v 1000 -r 30 -vf crop=w=in_w:h=in_h-200:x=0:y=0 -acodec ac3 -b:a 128 -ar 44100 -ac 2 "/boot/home/Desktop/Test.avi"

* Cropping 200 pixels from the **left** doesn't actually crop at all
   > ffmpeg -i "/boot/home/Desktop/Test.mp4" -f avi -vcodec mpeg4 -b:v 1000 -r 30 -vf crop=w=in_w:h=in_h:x=200:y=0 -acodec ac3 -b:a 128 -ar 44100 -ac 2 "/boot/home/Desktop/Test.avi"

* Cropping 200 pixels from the **right** works
   > ffmpeg -i "/boot/home/Desktop/Test.mp4" -f avi -vcodec mpeg4 -b:v 1000 -r 30 -vf crop=w=in_w-200:h=in_h:x=0:y=0 -acodec ac3 -b:a 128 -ar 44100 -ac 2 "/boot/home/Desktop/Test.avi"

* Cropping 200 pixels from the **all sides** only crops the right side
   > ffmpeg -i "/boot/home/Desktop/Test.mp4" -f avi -vcodec mpeg4 -b:v 1000 -r 30 -vf crop=w=in_w:h=in_h:x=0:y=200 -vf crop=w=in_w:h=in_h-200:x=0:y=0 -vf crop=w=in_w:h=in_h:x=200:y=0 -vf crop=w=in_w-200:h=in_h:x=0:y=0 -acodec ac3 -b:a 128 -ar 44100 -ac 2 "/boot/home/Desktop/Test.avi"

**Comment by andimachovec** [comment]
The code to generate the cropping commandline option probably needs to be reworked completely. It`s even stated in a comment above it. At the moment it stacks several filters upon each other, I´m not really surprised this doesn´t work correctly ;-)

**Comment by andimachovec** [comment]
@humdingerb : Could you check out my fix_cropping branch and test if it works with your examples?

**Comment by humdingerb** [comment]
Yep, seems to work fine!

**Comment by andimachovec** [comment]
Great, happy to hear that.

**Comment by andimachovec** [comment]
is fixed and can be closed
