### ISSUE TITLE
All encodes have a bad quality

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ffmpegGUI#47]
I only managed to make to mpeg4 mpeg encodes so far. The result always has bad quality, even when using 5000 kbits/s bitrate.

**Comment by andimachovec** [comment]
The values for video and audio bitrate are in bit/s on the ffmpeg commandline, so they need a "k" after the number to make sense with the values we supply from the gui. I´ve already fixed it in my local repo, will go into my next PR.

**Comment by humdingerb** [comment]
Fixed with #49
