### ISSUE TITLE
MediaConverter ticket #16831 just for your info

### ISSUE THREAD

**Issue by Brunobasta** [HaikuArchives/ffmpegGUI#48]
Can you solve this issue with FFmpegGUI?
Just for testing?

It is Just make you aware of MediaConverter problems for comparision!
Maybe it helps overall.

https://dev.haiku-os.org/ticket/16831

**Comment by Brunobasta** [comment]
an audioconverter maybe helpful for your info:
https://freac.org/

**Comment by andimachovec** [comment]
To answer your question, if I got this correctly from looking at the MediaConverter ticket. Yes,in general ffmpegGUI can convert AVI to MP4 with video and sound. To see if it can convert your specific video, you are encouraged to try for yourselves. I´d suggest waiting  until my next PR is submitted and merged, there are a few nasty bugs with wrong ffmpeg options in the current version. 
Apart from that, please don´t post any stuff relating to other apps here, unless it´s relevant to a specific bug or feature suggestion in ffmpegGUI. Thank you ;-)

**Comment by andimachovec** [comment]
@Brunobasta : My PR with the bugfixes is merged. You can test now if ffmpegGUI can convert your video. You can find instructions on how to build the app here: https://discuss.haiku-os.org/t/need-some-testing-of-ffmpeggui-for-upcoming-release/12795/8?u=bluesky

**Comment by andimachovec** [comment]
@Brunobasta : Please close this issue after reading my comment
