### ISSUE TITLE
Add "Source media info"

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ffmpegGUI#54]
It'd be nice to steal MediaPlayer's "File info" window, invoked with a new menu item "Source media info (ALT+I)" (plus possibly an "info" button after the "Source file" textbox):

![screenshot2](https://user-images.githubusercontent.com/6107158/208875468-3b9c37c0-d10c-4f13-a57a-9dc994b70248.png)

Of course without the "Display mode" and "Location" info.

Alternatively, or additionally as "Extended info" you can expand with some widget or similar to Expander's "Show contents" checkbox: use the external app "mediainfo" for more in-depth information.
Would mean more parsing of stuff, of course... :)

**Comment by humdingerb** [comment]
I see there's a mediainfo_devel package with heaaders and stuff, so the mediainfo stuff could possibly even be integrated better than just calling the mediainfo executable and parse its output.

**Comment by andimachovec** [comment]
Good idea, this is a very useful feature. I´m not sure if it should go into an extra window or just be displayed in a small font below the textview with the filename. Any thoughts on that?

**Comment by humdingerb** [comment]
Or, since the text boxes are wider than necessary, maybe a media info box beside them.
Mockup:

![mediainfo](https://user-images.githubusercontent.com/6107158/209140717-1dd61939-17a4-48cf-980b-d01efb3d8366.png)

I had to shorten the output popup labels. Probably a good idea inany case.

**Comment by andimachovec** [comment]
> maybe a media info box beside them.

Looks great, I like this. 

> I had to shorten the output popup labels. Probably a good idea inany case.

:+1:

**Comment by andimachovec** [comment]
> use the external app "mediainfo" for more in-depth information.
> Would mean more parsing of stuff, of course... :)

Since we are already working with the external ffmpeg this shouldn't be too complicated. I'd suggest we stay with the ffmpeg tools and use ffprobe to obtain the media info

**Comment by humdingerb** [comment]
Even better!

**Comment by humdingerb** [comment]
I'd like to give implementing this a try.
I may need a better coder than me to review the PR once it's done...

**Comment by andimachovec** [comment]
Done and can be closed
