### ISSUE TITLE
Use pre-defined values for "Audio" options? 

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ffmpegGUI#58]
Does it make sense to allow any arbitrary value for audio bitrate and sampling rate?

Maybe pop-ups with standard values are better.

Bitrates: 96, 128, 160, 196, 320, 1411 kbit/s (others?)
Sample rates: 22.05, 44.1, 48, 96 or 192 kHz

**Comment by andimachovec** [comment]
is done and can be closed
