### ISSUE TITLE
Increase step size of video bitrate

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ffmpegGUI#59]
The BSpinner steps for video bitrate should be 50 or 100. You normally don't need to in/decrease bitrates in 1 Kbit/s steps.

**Comment by andimachovec** [comment]
That annoyed me too. I always type in the values, which is not exactly what a spinner is for ;-) What's even more annoying is that BSpinner in its default form doesn't allow changing the increment/decrement value, so I have to subclass the whole thing to implement that. Not the end of the world but I thought this would be a quick one. 
//me stops being annoyed for today ;-)

**Comment by humdingerb** [comment]
Weird that there's no Step() / SetStep() as there is for BDecimalSpinner. Might be worth a Trac ticket...

**Comment by andimachovec** [comment]
Yes, I think it should be in BSpinner also. For more complicated stepping (e. g. non-linear) you have to subclass BSpinner (or BAbstractSpinner anyway, but setting a simple linear step should be possible without.
