### ISSUE TITLE
Allow 1:1 copy of audio/video

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ffmpegGUI#66]
Currently, disabling "Enable video / audio encoding" will remove the video / audio track.
It'd be useful to be able to opt for a 1:1 copy of audio or video.

The ffmpeg commands are apparently "-vcode copy" and "-acodec copy".

From the GUI side, the checkboxes to "Enable video / audio encoding" could be changed to radio buttons. For video, e.g.:

* 1:1 copy 
* Enable video encoding

And have the options below only enabled if "1:1 copy" isn't selected.
The "1:1 copy" option would override the "Output video format", because that must of course be the same as the source file's.

**Comment by humdingerb** [comment]
In the above 1:1 video copy, the output video format and the cropping options could be disabled, because cropping isn't allowed, of course.

**Comment by andimachovec** [comment]
> It'd be useful to be able to opt for a 1:1 copy of audio or video.

I've thought about this too. What about putting a "same as source" (or something similar) option into both video and audio format dropdowns. This way we wouldn't have to add any extra controls and enable the user to use the codec copy options for video and audio independently.

**Comment by humdingerb** [comment]
It may be, that the source is e.g. mpeg4 and a user wants to e.g. change the framerate or crop the picture, and keep the mpeg4-encoding. If the user chooses "same as source" it won't work. Or we don't disable the video/audio options below, the user changes some of those options, and doesn't realize he won't get a 1:1 copy when he misses how the "same as source" item above changes to some encoder (which one?).

I think it's a good idea to spell out "1:1 copy" to higlight that this is the lossless option.

**Comment by humdingerb** [comment]
After more consideration, maybe it would work to put the copy option in the output video/audio format menus. I'd go with "1:1 video/audio copy" though, to make it totally clear . And disable the not applicable options below.

**Comment by humdingerb** [comment]
@andimachovec: You think you'll get to finish your work on this soonishly, or should we rather prepare a release now and add this feature later?

**Comment by andimachovec** [comment]
> You think you'll get to finish your work on this soonishly
It's ready. Still need s a bit of work integrating with the recent changes, but should be done by tomorrow.

**Comment by humdingerb** [comment]
Great!
Once we got all the new/updated GUI strings, we can do any testing and polishing while we give the translators a week or so.

**Comment by andimachovec** [comment]
is implement in #85 and can be closed

**Comment by humdingerb** [comment]
Indeed, thanks!
