### ISSUE TITLE
Allow for non-integer framerates

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/ffmpegGUI#71]
The BSpinner currently only allows for integer frame rates.
We need to be able to set non-integer framerates like 23.976 or 29.97 or 59.94 frame/s, traditionally rooted in broadcasting (gained from dividing 24, 30, or 60 fps by 1.001).

Possible solutions I can think of:

* Don't use a BSpinner and allow any float in a simple BTextControl.
* Use a BDecimalSpinner (at least that's what I imagine it is used for, haven't found any code using it...) to allow for 3 decimal places. Ideally the spin buttons would still go in 1 fps steps, but e.g. after 23 we go to 23,976, then 24 etc.
    Also allow any arbitrary floats for weird amateur encodings...

**Comment by andimachovec** [comment]
I've never heard of non-integer framerates but BDecimalSpinner should be the way to go here.

**Comment by humdingerb** [comment]
Oh, they are/were abundantly used in broadcasting. The always fantastic Captain Disillusion has a video on framerate:
https://www.youtube.com/watch?v=DyqjTZHRdRs
