### ISSUE TITLE
Output tab is redundant

### ISSUE THREAD

**Issue by sdomi** [HaikuArchives/ffmpegGUI#9]
As the app is trying to launch a terminal app anyways (see #8), the output tab isn't needed. Another approach would be to deprecate the terminal and use the output tab for logs, but it doesn't work that way at the moment.

**Comment by andimachovec** [comment]
I'm currently working on a patch to execute the ffmpeg commandline directly from the app without the use of Terminal. That opens the possibility to show the output from ffmpeg in the output tab, as well as other things like progress bar and error checking/reporting.
